site:
  title: GDCubism
  url: https://mizunagikb.github.io/gd_cubism/
  start_page: gd_cubism::ja/index.adoc
content:
  sources:
    - url: https://github.com/MizunagiKB/gd_cubism.git
      branches: [0.6, 0.7, 0.8, 0.9]
      start_path: docs-src
ui:
  bundle:
    url: https://github.com/MizunagiKB/gd_cubism_ui/releases/download/v1.0.0/ui-bundle.zip
output:
  dir: docs
antora:
  extensions:
    - require: "@antora/lunr-extension"
      languages: [ja, en]
